directories:
  output: dist-electron
  buildResources: build
asar: false
appId: com.quantmind.desktop
productName: QuantMind Desktop
files:
  - filter:
      - src/**/*
      - dist/**/*
      - assets/**/*
      - node_modules/**/*
asarUnpack:
  - src/bot/**/*
win:
  target: nsis
  icon: assets/icon.ico
  requestedExecutionLevel: asInvoker
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: QuantMind Desktop
  installerIcon: assets/icon.ico
  uninstallerIcon: assets/icon.ico
  perMachine: false
publish:
  - provider: generic
    url: http://74.162.152.95:3001/updates
electronVersion: 22.3.27
